### ISSUE TITLE
Release tag

### ISSUE THREAD

**Issue by wikimatze** [sk1418/blockit#3]
There is none, can you create one?

Thanks!

**Comment by sk1418** [comment]
@wikimatze I added one. When I clicked your name, took a look your recent activities, I noticed that, you seem like a "releaseTagReminder-Robot@github". ^_*  Thank you.

**Comment by wikimatze** [comment]
Thanks for releasing, and I like to be still a human being and no robot :smiley: - I always wanted to get tags for all the plugins I'm using and I went through all them to remind the authors of their latest releases.

**Comment by sk1418** [comment]
great!
glad to know that you are using blockit.

**Comment by wikimatze** [comment]
Jup, it's great for drawing and commenting big blocks, always looking to improve the plugins and encourage authors like you to go on with the development.

**Comment by sk1418** [comment]
well if you meant my blockit, I don't know what useful features I could bring into.  I wrote it because some day I had to draw many those rectangles.  Btw, if you need "draw" things, you may want to take a look a plugin: "DrawIt", it can block text/lines too, but not so easy as blockit does. However it provides more features than blockit, really feel like drawing. it is an old plugin, but still working.

**Comment by wikimatze** [comment]
Thanks for the advice, I know DrawIt but found your easier to handle and to use.
